import type { Metadata } from "next";
import "./globals.css";
import "antd/dist/antd.css"

import Footer from "../components/Footer"
import Navbar from "../components/Navbar";
import {StoreProvider} from '../../store'
import {getCookie} from '../../utils'

interface IProps{
  initialValue: Record<any, any>;
  children: React.ReactNode;
  pageProps: any;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({children, pageProps}: IProps){
  let userId = getCookie('userId')
  let nickname = getCookie('nickname')
  let avatar = getCookie('avatar')
  const initialValue = {
    user: {
      userInfo: {
        userId,
        nickname,
        avatar
      }
    }
  }
  
  const renderLayout = ()=>{
    return (
      <div>
        <Navbar />
        {children}
        <Footer />
      </div>
    )
  }

  return (
    <html lang="en">
      <body>
        <StoreProvider initialValue={initialValue}>
          {renderLayout()}
        </StoreProvider>
      </body>
    </html>
  )
}

export default RootLayout